<?php  
$titre = "Mentions légales";
echo "<h1>$titre</h1>";
?>
<!-- ((h2>lorem2)+p*3>lorem40)*8 -->
<h2>Lorem, ipsum.</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse ea ipsa harum illum laboriosam nemo. Ipsum vitae magnam laboriosam corporis sed autem, non beatae est inventore culpa ut? Corporis numquam natus iste porro vero hic tempora? Eveniet harum velit suscipit!</p>
<p>Delectus odio distinctio rerum porro impedit vitae? Perferendis temporibus recusandae placeat alias iusto voluptate? Veritatis magni perferendis facere doloribus, eius tenetur aliquam delectus neque sint dicta totam architecto placeat. Fuga totam vitae iure nihil officiis sit impedit doloribus sed quo?</p>
<p>Sunt commodi ad reprehenderit maxime ipsum dignissimos, cupiditate quo molestias eaque debitis id fugiat ut voluptates numquam perferendis fuga et? Officiis similique quis cumque ullam, provident exercitationem praesentium deserunt vero sint. Ex, illum recusandae! Beatae, dignissimos suscipit? Dolores, eveniet ad.</p>
<h2>Sequi, libero?</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, ratione voluptatibus, soluta cumque repellendus repudiandae, delectus ut eius veniam aliquid ea voluptas magni. Est deserunt deleniti quos dolor, quod, ducimus delectus itaque quae at iusto facilis aperiam dolore? Dignissimos, similique.</p>
<p>Quas, impedit alias. Minus dolorem molestias porro neque. Natus exercitationem corrupti aliquam nulla reprehenderit facilis quidem eum quo? Placeat accusantium obcaecati exercitationem velit? Neque cupiditate alias, excepturi, eum totam laborum autem officia consectetur temporibus libero animi quas commodi quae facere?</p>
<p>Aut corrupti quibusdam ullam accusamus tenetur enim praesentium eligendi tempora vero, commodi quasi impedit eum recusandae cupiditate? Laboriosam temporibus nisi praesentium veniam fuga excepturi provident, voluptatem ad consequuntur? Facere nostrum harum cumque adipisci dolores repudiandae tempora dignissimos suscipit soluta rem?</p>
<h2>Doloremque, praesentium.</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci reprehenderit vel nihil vitae fuga assumenda in et cupiditate minus rem provident laboriosam nisi error sapiente officiis architecto, illum fugit quam ipsa nesciunt. Vero magnam earum itaque, cum ducimus dolor placeat.</p>
<p>Doloremque reprehenderit tempora possimus? Totam quae facere rerum placeat ipsam eos quaerat unde aspernatur, voluptates assumenda quas eveniet nobis ullam nesciunt vitae quod exercitationem vero voluptatum rem nemo dolorum ipsum molestias! Temporibus, quisquam. Quibusdam, corporis ab! Natus, incidunt aliquid? Rerum?</p>
<p>Accusamus suscipit quisquam at corrupti obcaecati, inventore error. Laborum voluptates at eligendi facilis quos aspernatur velit rerum nisi inventore consectetur numquam dolores porro ullam facere nulla, quia assumenda animi? Qui doloribus magni quia fuga cupiditate odio voluptas animi consequatur numquam.</p>
<h2>Illum, omnis.</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis doloribus necessitatibus laudantium odit a nobis expedita, eaque perspiciatis assumenda aut, obcaecati sapiente nesciunt. Eos omnis fugiat, dolorum id reiciendis minima aliquam eveniet rerum sint, ipsa maiores nemo magnam, doloribus accusamus.</p>
<p>Ea tempora enim sed veniam doloremque ratione suscipit delectus beatae quasi numquam facilis rem, voluptate praesentium. In aliquid dolore ullam eius voluptates exercitationem, quidem perferendis rem reprehenderit modi quam cupiditate maiores, nisi fugiat quisquam placeat beatae amet facilis. Quam, sed.</p>
<p>Quia, minima rerum recusandae quidem libero, facere hic ullam dolor eligendi maxime veniam voluptate temporibus fugiat odit distinctio cupiditate saepe nesciunt est, ea similique. Perspiciatis enim hic repellendus nisi dicta, dignissimos, fugit at corporis suscipit maxime beatae animi esse ex.</p>
<h2>Eaque, at.</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate quas reprehenderit nobis ex libero. Minima libero, eaque consectetur in sunt maiores hic quam! Neque repellendus id laboriosam ullam enim quidem quos blanditiis nostrum! Hic maxime modi ullam vel nisi impedit?</p>
<p>Iure exercitationem aspernatur voluptas dolor animi alias optio officia, unde dolores sed ut magni possimus reprehenderit odio beatae, minima eligendi sequi voluptatum debitis quasi quis laboriosam, repellendus qui facilis. Quam soluta iusto perspiciatis expedita suscipit, iure amet quisquam vitae nisi.</p>
<p>Quibusdam esse neque repudiandae fuga ratione impedit beatae aut vitae aspernatur harum a porro quo eveniet cupiditate laudantium, voluptatum qui amet repellendus! Neque suscipit quos iusto, minus asperiores accusamus mollitia aut exercitationem quam necessitatibus dolor praesentium cupiditate nesciunt fugiat assumenda!</p>
<h2>Nisi, repellendus.</h2>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Pariatur temporibus perspiciatis quos esse natus mollitia ad ex quidem voluptatibus cum. Corrupti sunt porro eum vero fuga cum quae, odit ipsum ea incidunt debitis deserunt esse distinctio ad dolorum dignissimos sed!</p>
<p>Corrupti, consequatur vel dignissimos dicta cupiditate sapiente officiis. Vel sequi corporis praesentium sint ab. Natus amet quasi, ipsum placeat qui officiis blanditiis assumenda impedit, voluptatem eaque, facilis modi nihil magni error at. Excepturi error tempore sapiente, inventore recusandae aperiam expedita!</p>
<p>Quisquam fugit, maxime, saepe inventore a commodi delectus molestias ea rerum sint quaerat consectetur dolor, impedit alias. Blanditiis, sed aut excepturi nobis adipisci, consequuntur harum aliquid eveniet asperiores sunt itaque possimus assumenda, optio quas odio nostrum! Possimus ea consequatur distinctio?</p>
<h2>Impedit, repellat.</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, ullam molestias quo commodi est, libero excepturi inventore quae tenetur obcaecati blanditiis! Iusto, provident dolor accusamus, sed, aliquid omnis corporis esse nihil incidunt corrupti repellendus totam saepe recusandae architecto earum voluptatem!</p>
<p>Modi alias architecto iusto temporibus explicabo illo repellendus in aperiam error numquam ex, iste tempora vel aliquid. Labore quas eos, ipsum magnam id rem aliquam? Voluptate veritatis corrupti provident quos. Provident laudantium quisquam, quidem omnis voluptatem modi quas iusto reiciendis.</p>
<p>Consectetur nesciunt exercitationem, eveniet numquam rerum recusandae aliquid atque eos veniam unde delectus impedit animi fuga iste, ex odit magnam. Tempora reiciendis quod nisi atque, nesciunt maiores porro eos dolorem neque ea, quia fugit. Ratione expedita modi excepturi voluptate voluptatem?</p>
<h2>Esse, aliquid!</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus maiores mollitia fuga explicabo, quos atque unde autem quam provident veniam asperiores, assumenda ipsum sunt nam modi debitis perferendis, error optio nemo ex commodi facilis vero sapiente dolor. Neque, nesciunt ducimus?</p>
<p>Quas, minus. Doloremque aut recusandae fugiat consequuntur nesciunt optio quibusdam deleniti, maxime velit architecto quam non exercitationem voluptatum facere accusamus aperiam dolores error voluptatibus! Tempora voluptas inventore ullam at quam voluptates commodi minus, quibusdam ratione amet ab velit eaque nemo.</p>
<p>Exercitationem impedit cupiditate obcaecati doloremque incidunt voluptatum ex aliquid praesentium nisi nemo magni, eum, odio quis beatae, soluta fugiat cum modi nesciunt possimus fuga earum facilis distinctio eaque voluptates. Vitae quia neque repudiandae sequi odio aspernatur distinctio, maxime soluta fugit?</p>